radicle-dev/radicle-link

Cargo.lock, librad2/src/keys/pgp.rs, librad2/src/keys/storage.rs, rad2/Cargo.toml, rad2/src/commands/keys.rs, rad2/src/commands/mod.rs, rad2/src/error.rs, rad2/src/main.rs, rad2/src/pinentry.rs
Not terribly useful, but gets the CLI scaffolding in place.
=> CLI: Show + create device key

Cargo.lock, librad/Cargo.toml, librad/src/git/mod.rs, librad/src/keys/device.rs, librad/src/keys/pgp.rs, librad/src/keys/storage.rs
=> Upgrade sequoia-openpgp

Cargo.lock, librad/Cargo.toml, librad/src/git/mod.rs
Catch up with the latest changes in the radicle-surf and adjust calls
where necessary.
=> Bump radicle-surf dependency

librad/src/git/mod.rs
Also push the default branch ref to the rad remote, and set HEAD accordingly.
We can't teach ligit to /not/ create a HEAD ref, so make it valid at least.
=> Honor the metadata `default_branch` as the init parent

.buildkite/docker/rust-nightly/Dockerfile, .buildkite/docker/rust/Dockerfile, .buildkite/pipeline.yaml, .rustfmt.toml
=> Add .rustfmt.toml and matrix build against rust stable + nightly

Cargo.lock, librad/Cargo.toml
So we can reap the latest and greatest features in the application.
=> Bump radicle-surf to latest commit

README.md
I had to change dev workstation and I noticed that the project does not build out of the box on a plain linux install.
Maybe these instructions will help somebody...
=> Added build env instructions.

librad/examples/mesh.rs, librad/src/net/gossip.rs, librad/src/net/gossip/rpc.rs, librad/src/net/gossip/storage.rs, librad/src/net/protocol.rs
There's a few rustisms I don't really get, see self-review
=> Parametrise gossip message payload

Cargo.lock, librad/Cargo.toml, librad/src/lib.rs, librad/src/peer.rs, librad/src/uri.rs
URN and URL types as per #65
Closes #65
=> Introduce uri module

librad/src/net/gossip.rs, librad/src/net/protocol.rs
This provides the online part of `Browse::query` from #82. As stated there, the protocol may also have cached information about providers, which is not part of this patch.
=> Return a stream of provider responses at the protocol layer

librad/src/hash.rs, librad/src/uri.rs
Note that `Hash` is not forward-compatible, ie. an earlier version of the software will refuse to handle a hash algorithm introduced later. Perhaps this is what @massimiliano-mantione's doubts were. 
I don't have a good solution for how to solve this, since we assume that we must stay compatible with `registry`. I am, otoh, also not sure where this requirement came from, respectively what hash the `registry` wants to verify, and based on which input data.
=> Make RadUrn identified by Hash instead of Multihash

Cargo.lock, librad/Cargo.toml, librad/src/net.rs, librad/src/net/connection.rs, librad/src/net/gossip.rs, librad/src/net/gossip/rpc.rs, librad/src/net/gossip/types.rs, librad/src/net/protocol.rs, librad/src/net/quic.rs, librad/src/net/upgrade.rs, librad/src/uri.rs
Also:
* introduce a simple mock stream and add a basic test for upgrades
* abstract over `SocketAddr` in gossip, to pave the way for testing
using the mock stream
=> Factor out protocol upgrade

.buildkite/docker/rust-nightly/Dockerfile, .buildkite/pipeline.yaml, librad/examples/mesh.rs, librad/src/canonical.rs, librad/src/git.rs, librad/src/git/refs.rs, librad/src/git/repo.rs, librad/src/git/transport.rs, librad/src/git/url.rs, librad/src/hash.rs, librad/src/keys/device.rs, librad/src/lib.rs, librad/src/meta/entity.rs, librad/src/meta/entity/data.rs, librad/src/meta/entity_test.rs, librad/src/meta/project.rs, librad/src/net.rs, librad/src/net/gossip.rs, librad/src/net/gossip/storage.rs, librad/src/net/peer.rs, librad/src/net/peer/types.rs, librad/src/net/tls.rs, librad/src/peer.rs, librad/src/uri.rs, librad/tests/logging.rs, librad/tests/propagation_basic.rs, librad/tests/testnet.rs
=> Stateful peer

CODEOWNERS
This seemed to create more noise than signal
=> Remove upstream-proxy from CODEOWNERS

librad/src/keys/device.rs
=> Future-proof PublicKey and Signature serde

docs/rfc/identity_resolution.md
[Rendered](https://github.com/radicle-dev/radicle-link/blob/rfc/identity-resolution/docs/rfc/identity_resolution.md)
=> RFC: Identity Resolution

librad/src/hash.rs, librad/src/meta/entity.rs, librad/src/meta/entity/data.rs, librad/src/meta/entity_test.rs, librad/src/meta/project.rs, librad/src/meta/user.rs, librad/src/uri.rs, librad/tests/propagation_basic.rs
=> Made EntityData typed (fixes #115).

librad/src/git/repo.rs, librad/src/git/storage.rs
=> Fix the `Tracked` iterator

librad/src/meta/entity.rs, librad/src/meta/entity_test.rs
=> Simplified entity sign methods (fixes #161).

librad/src/net/peer.rs
=> Expose Paths in PeerApi

docs/rfc/identity_resolution.md
"to simply the presence" should be "to simply mean the presence"
=> Patch the grammar

Cargo.lock, librad/Cargo.toml
=> Update radicle-surf dependency

librad/src/git/storage.rs, librad/src/meta/entity.rs, librad/src/meta/entity/data.rs
Fixes #142 
Allows us to list entities and apply a filter if we want to target one kind specifically.
=> List Entities

librad/src/internal/channel.rs, librad/tests/testnet.rs
Because both are needed to pass CI.
=> Combo of #192 + #193

librad/src/net/protocol.rs
Emit an explicit event similar to the tracing for consumers to reason about the successful startup of the peer.
=> Emit protocol Listening event

librad/src/git/ext.rs, librad/src/git/ext/error.rs, librad/src/git/ext/transport.rs, librad/src/git/p2p.rs, librad/src/git/p2p/server.rs, librad/src/git/p2p/transport.rs, librad/src/git/p2p/url.rs, librad/src/git/storage.rs, librad/src/git/storage/fetch.rs, librad/src/net/peer.rs, librad/src/net/protocol.rs, librad/src/net/upgrade.rs
In preparation of a local transport to interact with the storage repo.
=> Factor p2p git transport (both ends) under new module

git-helpers/tests/remote.rs
`git-credential-cache` seems to fail from time to time (perhaps that's a
feature?). Use a shell snipped to bypass it, in order to prevent CI
hangs.
=> git-helpers: Use shell snippet as credential helper

docs/rfc/identity_resolution.md, librad/src/git/repo.rs, librad/src/git/storage.rs, librad/src/git/storage/fetch.rs, librad/src/git/storage/test.rs, librad/src/git/types.rs
* Remove `refs` portion under `$TRACKED_PEER_ID`
* Add `rad/refs`
=> Update spec graph

librad/src/git/storage.rs, librad/src/git/types.rs
Fixes #244 
Adds a new struct called SymbolicRef which is the data needed for
creating a symbolic reference from an existing git reference. We use
this to clean up the creating of symbolic references in Storage.
=> Add SymbolicRef

Cargo.lock, git-helpers/Cargo.toml, git-helpers/src/remote_helper.rs, git-helpers/tests/remote.rs, librad-test/src/rad/testnet.rs, librad/Cargo.toml, librad/src/git/local/transport.rs, librad/src/git/refs.rs, librad/src/git/repo.rs, librad/src/git/storage.rs, librad/src/git/storage/config.rs, librad/src/git/storage/test.rs, librad/src/keys.rs, librad/src/lib.rs, librad/src/meta/entity.rs, librad/src/meta/entity_test.rs, librad/src/meta/user.rs, librad/src/net/peer.rs, librad/src/net/quic.rs, librad/src/net/tls.rs, librad/src/peer.rs, librad/src/signer.rs, librad/tests/propagation_basic.rs
=> Signers Everywhere

librad/src/net/quic.rs
When a TLS session is resumed (which is enabled by default), rustls doesn't
remember the presented certificate, and doesn't provide a way to attach
additional session persistence information. However, in the case of incoming
connections, we can still fall back to the SNI (relying on the cert verifier to
require SNI). Outgoing connections know the SNI already, so they can use that
by the same reasoning.
=> Determine remote identity when TLS session is resumed

docs/spec/identities.md, docs/spec/references.bib
[Rendered](https://github.com/radicle-dev/radicle-link/blob/spec/identities/docs/spec/identities.md)
=> Spec: Identities

librad/src/git/types/remote.rs
We may not want to create a remote with a fetchspec, so we leave it as
optional and branch on this deciding how we set up the remote.
=> Make the fetchspec optional

docs/spec/identities.md, spec/references.bib
Companion to #283 
[Rendered](https://github.com/radicle-dev/radicle-link/blob/spec/identities/payload/docs/spec/identities.md)
=> Spec: Identities Payload

librad/src/git/trailer.rs
Unifying an error type with a lifetime is not practical most of the
time: the error typically outlives the input.
=> Trailers: make error own its data

librad/src/git/trailer.rs
We need to be able to filter a `Trailer` list by `Token`, hence need to
be able to construct one.
=> Trailers: allow to construct a `Token` from a &str

librad/src/git/trailer.rs
Converting some type into a `Trailer` likely involves some
serialisation, which yields an owned string.
=> Trailers: turn values into cows

librad/src/git/trailer.rs
There are some lifetime gymnastics involved here, not all of which I was able to
sort out. Specifically, I'd prefer to implement `DisplayMany` for any opaque
`Iterator`, but oh my...
Also note how disappointingly type inference fails if you pass a closure to
compute the separator.
=> Trailers: rendering (via Display), with customisable separator

librad/src/git/storage.rs, librad/src/git/storage/test.rs, librad/src/net/peer.rs
=> Relevant peer announcements

librad/src/signer.rs
=> Implement BoxedSigner from Secretkey

librad-test/src/rad/testnet.rs, librad/src/net/gossip.rs, librad/src/net/peer.rs, librad/tests/propagation_basic.rs
Test the `PeerApi::providers` function
=> Test PeerApi::providers

Cargo.lock, deny.toml, git-helpers/tests/remote.rs, librad-test/src/rad/testnet.rs, librad/Cargo.toml, librad/src/git/storage/test.rs, librad/src/keys.rs, librad/src/lib.rs, librad/src/meta/entity_test.rs, librad/src/uri.rs, librad/tests/working_copy.rs
Closes #315 
~~Everything compiles with patched `ed25519-zebra`, however tests fail. I'm pretty sure the serialization changes broke it.~~
=> Switch crypto to ed25519-zebra

Cargo.lock, librad/Cargo.toml, librad/src/git/ext/oid.rs, librad/src/identities.rs, librad/src/identities/delegation/direct.rs, librad/src/identities/delegation/indirect.rs, librad/src/identities/generic.rs, librad/src/identities/generic/error.rs, librad/src/identities/generic/gen.rs, librad/src/identities/generic/tests.rs, librad/src/identities/git.rs, librad/src/identities/git/error.rs, librad/src/identities/git/iter.rs, librad/src/identities/git/load.rs, librad/src/identities/git/sign.rs, librad/src/identities/git/tests.rs, librad/src/identities/git/tests/common.rs, librad/src/identities/git/tests/project.rs, librad/src/identities/git/tests/user.rs, librad/src/identities/payload.rs, librad/src/identities/sign.rs, librad/src/identities/urn.rs, librad/src/internal/canonical.rs, librad/src/keys.rs
=> Identities: git implementation

librad/tests/propagation_basic.rs
Adding a test to confirm the expected steps of asking for a RadUrn
and having to clone from the PeerId that responded.
=> Ask and clone a project

librad/src/git/include.rs
If no mutations are done to the `git2::Config` it does not create the
file on disk. To ensure that the most up-to-date version is written, the
file is touched.
=> Ensure temporary include file is created

librad/src/git/include.rs
=> Prevent potential cross-filesytem rename when creating include

librad/src/net/connection.rs, librad/src/net/gossip.rs, librad/src/net/protocol.rs, librad/src/net/quic.rs, librad/src/net/upgrade.rs
The is no reason for the roundtrip, so better make this change now.
Also, refine the CBOR encoding of UpgradeRequest.
Note that this is a breaking change.
=> Networking: 0RTT stream upgrade

librad/src/net/quic.rs
While not terribly useful for a multiplexing protocol, we establish this
now in order to allow for future major protocol upgrades.
=> Networking: establish ALPN

docs/spec/identities.md, spec/references.bib
Thanks @rudolfs for beating me to it!
=> Specify URNs

docs/spec/identities.md, spec/references.bib
I couldn't find a clear definition of URNs anywhere in the docs when doing my research for https://github.com/radicle-dev/radicle-upstream/issues/840, and thought it might be a good idea to write down my findings.
Note: the style might not match the rest of the document yet, I'm open for suggestions!
=> Add a section about URNs

librad/src/net/gossip.rs
=> Gossip: Fix shuffle random walk termination condition

librad/src/git/local/transport.rs
Dreadful, but the wait thread may actually terminate when _everything
else_ has been dropped already. When using temporary directories for
tests, this leads to a race where the post-service hook is run after the
tempdir was already destroyed.
---
Fixes https://github.com/radicle-dev/radicle-upstream/pull/1010#issuecomment-705558553
=> Transport: Rely on destructors for wait(2)

CODEOWNERS
Such automatation, much pointing-devicelessness
=> Add that missing globstar to CODEOWNERS

librad/src/git/local/transport.rs
We may otherwise wrongly terminate the child, where we simply haven't received SIGCHLD yet.
---
Astonishing that a sytems programming language doesn't have better, cross-platform tools for these kinds of things in the standard library. Most likely, this will totally not work on Windows.
=> Transport: Busy-wait for SIGCHLD

librad/src/net/protocol.rs
=> Expose connected peers

librad/src/git/include.rs, librad/src/git/local/transport.rs, librad/src/git/p2p/server.rs, librad/src/git/p2p/transport.rs, librad/src/git/refs.rs, librad/src/git/storage.rs, librad/src/git/storage/config.rs, librad/src/git/types.rs, librad/src/git/types/namespace.rs, librad/src/git/types/reference.rs, librad/src/git/types/remote.rs, librad/src/hash.rs, librad/src/identities/gen.rs, librad/src/identities/git.rs, librad/src/identities/git/load.rs, librad/src/identities/payload.rs, librad/src/identities/sealed.rs, librad/src/identities/urn.rs, librad/src/lib.rs, librad/src/peer.rs, librad/tests/propagation_basic.rs, librad/tests/working_copy.rs
Otherwise this is all going to end in **cargo hell**.
Note about the aliasing: I know people have **opinions** about aliasing, but **my opinion** is that this particular aliasing the most **gentle on the eyes**.
=> Re-export git-ext, std-ext and macro crates through librad

seed/src/lib.rs
Ensure replication of project updates coming from different peers the the one first observed.
=> seed: fetch and track when existing

librad/src/net/protocol.rs
The try operator in the loop would return the outter method, preventing
that the `handle_disconenct`, necessary to fire the disconnecting event,
is ever reached.
Closes #393
=> protocol: fix handle disconnect for incoming

librad/src/net/peer.rs
If we don't have a `refs/` prefix when calculating the urn_context, then
we assume that the reference name is expecting a `heads/` prefix.
=> Qualify path in urn_context

docs/spec/identities.md, librad-test/src/rad/identities.rs, librad/src/git/identities.rs, librad/src/git/identities/local.rs, librad/src/git/identities/person.rs, librad/src/git/include.rs, librad/src/git/replication.rs, librad/src/git/storage/config.rs, librad/src/identities/delegation/direct.rs, librad/src/identities/git.rs, librad/src/identities/git/error.rs, librad/src/identities/git/load.rs, librad/src/identities/git/tests.rs, librad/src/identities/git/tests/common.rs, librad/src/identities/git/tests/person.rs, librad/src/identities/git/tests/project.rs, librad/src/identities/payload.rs, librad/tests/propagation_basic.rs, librad/tests/working_copy.rs, seed/src/lib.rs
=> Users are persons

deny.toml, git-helpers/tests/remote.rs, librad-test/src/rad/testnet.rs, librad/Cargo.toml, librad/src/keys.rs
=> keys: remove Copy impl for SecretKey and zero memory on drop

librad/src/net/peer.rs
When we receive a `Have` messages for a URN we are tracking we will fetch the repo even if no `branch` is set in the `Have` message. This allows us to receive ref updates and solves https://github.com/radicle-dev/radicle-upstream/issues/1242.
=> Apply Have’s for tracked URNs even if no rev is set

librad/src/lib.rs, librad/src/net/protocol.rs
Try to establish connections to all given addresses concurrently, and pick the first successful.
=> protocol: connect concurrently

librad/src/net/peer.rs
When we receive a `Have` messages for a URN we are tracking we will
fetch the repo even if no `branch` is set in the `Have` message. This
allows us to receive ref updates and solves https://github.com/radicle-dev/radicle-upstream/issues/1242
=> forward-port: Apply Have’s for tracked URNs even if no rev is set (#438)

librad/src/net/quic.rs
* Set keep alive interval to recommended 30s
* Make only one end send keep alive probes at all
* Set idle timeout (on the other end) to tolerate loss of 1-2 keep-alive
probes
=> net: revisit transport params

librad/src/net/gossip.rs, librad/src/net/protocol.rs
=> net: guard against a panic when connecting

Cargo.toml, e2e/Cargo.toml, e2e/Procfile, e2e/README.md, e2e/localnet, e2e/src/bin/ephemeral-peer.rs, e2e/src/lib.rs, e2e/src/logging.rs, e2e/theus/config.yaml, librad/src/net/peer.rs
Rudimentary automation for spawning networks onto the loopback
interface.
=> e2e: basic setup

librad/src/git/replication.rs
We were adding the elements into the wrong sets (booleans gouged out my
eyes). This patch fixes the logic and adds some proptests to ensure I
know I what I'm doing (hint: I don't).
=> Correct partition logic

librad/src/net/protocol/io.rs
=> protocol: abandon ingress only on some errors

.github/workflows/fast.yaml, ci/macos-gnu
=> GHA: Fix the macos builds by using GNU

librad/src/net/protocol.rs, librad/src/net/protocol/accept.rs, librad/src/net/protocol/control.rs
=> net: Factor out downstream control messages into separate module

librad/src/git/identities/any.rs, librad/src/git/identities/error.rs, librad/src/git/replication.rs, librad/src/net/protocol.rs, librad/src/net/protocol/accept.rs, librad/src/net/protocol/control.rs, librad/src/net/protocol/error.rs, librad/src/net/protocol/error/internal.rs
Makes visibility more obvious.
=> net: Split public and internal protocol errors

librad/src/net/protocol/membership/partial_view.rs
When we add active we never checked to remove them from the passive
list. This means we end up double counting a peer.
=> membership: ensure parity with active and passive members

librad/src/net/protocol/membership/partial_view.rs, librad/src/peer.rs
=> membership: property tests

librad/src/git/tracking.rs
Some unlucky invocations would falsely write empty remotes to the sigrefs.
=> git: Fix Tracked iterator to ignore URN path

seed/src/lib.rs, seed/src/signer.rs
Stacked on #565 
Allows us to tune the seed's configuration parameters.
=> seed: expose config parameters

librad/src/identities/payload.rs
Motivated by the need to remove an Ethereum claim ext in the Upstream,
which is done by removing claim.
=> identities: add remove_ext to Payload

librad/src/git/replication.rs, librad/tests/scenario/menage.rs
In the clone path of replication we only kept the delegate peers. We
would also want to keep the tracked peers to preserve the tracking
graph.
This patch also adds a test in our menage scenario to confirm a 3rd
peers sees the other 2 peers collab'ing.
=> replication: ensure we don't prune tracked peers

.buildkite/pipeline.yaml, .github/workflows/fast.yaml
Also, GHA seems to not correctly evaluate `== true|false`.
=> ci: don't skip buildkite steps if not a PR

docs/index.html, docs/radicle-link.pdf
Rendering the RFCs would just be too laborious. Perhaps they could be
added as appendices to the spec at some point.
Closes #531
=> spec: make rendered html the GH pages index

librad/src/net/quic/connection/tracking.rs
There is a potential race when tickles get delayed for some reason
(maybe because we're waiting on I/O?).
Also, use SeqCst ordering throughout, until I feel I grok the C++ memory
model, which might be never.
=> net: bump tracked conn epoch when not reaped

data/Cargo.toml, data/src/bounded.rs, data/src/lib.rs, data/src/nonempty.rs
Adds newtypes witnessing the "length" of a type to be within a range.
=> data: add bounded types

data/Cargo.toml, data/src/bounded.rs, data/src/lib.rs, data/src/nonempty.rs, e2e/compose.yaml
=> e2e: pass through RUST_LOG to compose

data/src/bounded.rs, data/src/nonempty.rs
Instead of the lawless Default trait, use std::iter structs with the
desired properties.
=> data: improve construction for known-to-be-within bounds values

librad/src/git/fetch.rs
Signed-off-by: Alex Good <alex@memoryandthought.me>
=> Increase the fetch limit for peeks to 5Mb

.buildkite/pipeline.yaml, daemon/src/state.rs, daemon/src/state/error.rs
=> daemon: add missing spawn_blocking

.buildkite/pipeline.yaml
_this commit message ran for over 60 seconds_
=> ci: add step timeouts

.buildkite/env
=> ci: remove bk cache dir when <25% of the quota is available

daemon/src/peer/announcement.rs, daemon/src/peer/subroutines.rs, daemon/src/state.rs
=> daemon: hunt down more missing spawn_blocking

seed/Cargo.toml, seed/src/handle.rs, seed/src/lib.rs
See single commits for rationale and context.
=> seed: Improve resilience

.buildkite/env
Fix df target, add some debug output, turn off incremental compilation
for good.
=> ci: space fixes

data/src/bounded.rs
Reifying the bounds phantom types for Debug.
=> data: implement Debug + Display for Within

docs/rfc/0685-noise.adoc
[Rendered](https://github.com/radicle-dev/radicle-link/blob/rfc/noise/docs/rfc/0000-noise.md)
=> RFC: Noise Protocol

daemon/src/peer/announcement.rs, daemon/src/state.rs, test/src/daemon/common.rs, test/src/test/integration/daemon/gossip.rs
This fixes an issue with users not seeing each others' updates, e.g. of Ethereum claims
=> daemon: Announce user updates

librad/src/net/protocol.rs, librad/src/net/protocol/membership/hpv.rs, librad/src/net/protocol/membership/periodic.rs
We create a stream with periodic membership tasks that needs to be pulled instead of spawning a tasks that pumps the membership tasks into a channel. This has the advantage that now detached task needs to be spawned and that we stop issuing membership tasks when future retuned by `accept()` is dropped.
=> librad: pull periodic tasks instead of spawning

daemon/src/peer.rs, seed/src/lib.rs, test/src/daemon/common.rs
`Peer::run` now properly cleans up the network stack when run to
completion. To this end it accepts a shutdown signal as an argument.
This seems to fix [deadlocks][1] that occur when the daemon is torn down
multiple times.
Instead of copying the approach from `seed/src/lib.rs` we use a shutdown
future and port this approach to the seed. The reason for this is that
the seed also did not handle shutdown properly. If a termination signal
was sent it did not break the main loop. Moreover we did not react to
shutdown requests while awaiting `peer.bind()`.
[1]: radicle-dev/radicle-upstream#2133
=> daemon: call protocol cleanup when peer is dropped

Cargo.toml, clib/Cargo.toml, clib/README.md, clib/src/keys.rs, clib/src/lib.rs, clib/src/ser.rs, clib/src/storage.rs
=> clib: introducing common CLI data types and functions

daemon/src/peer/announcement.rs, librad/src/git/identities/error.rs, librad/src/git/storage/config.rs, librad/src/identities/urn.rs
=> identities: split out URN parsing from just an id

daemon/src/peer/run_state/running_waiting_room.rs
We stop persisting the waiting room on the `Tick` input. The waiting room state itself does not change when this input is processed. Since the waiting room tick occurs every 500ms by default the serialization load might be heavy.
Similarly, we eliminate the `Tick` waiting room event since it offer no valuable information.
=> daemon: don’t persist waiting room on tick

clib/src/ser.rs
=> clib: add FromStr and other impls for Format

git-ext/src/blob.rs, librad/src/git/refs.rs, librad/src/git/storage.rs, librad/src/git/storage/read.rs
Also seen [here](https://lists.sr.ht/~radicle-link/dev/%3C20210903083251.25059-1-kim%40eagain.st%3E)
=> preserving the commit oid of loaded sigrefs

.buildkite/pipeline.yaml, bins/Cargo.toml, bins/rad-identities-dev/Cargo.toml, bins/rad-identities-dev/src/main.rs, bins/rad-profile-dev/Cargo.toml, bins/rad-profile-dev/src/main.rs, bins/rad/Cargo.toml, bins/rad/src/main.rs, ci/build-bins, rad-clib/Cargo.toml, rad-exe/Cargo.toml, rad-exe/src/cli/args.rs, rad-exe/src/cli/main.rs, rad-identities/Cargo.toml, test/src/test/unit/rad_exe/args.rs
Since we now have a `bins` section, I'm adding the `rad`, `rad-identities-dev`, and `rad-profile-dev` binaries there. Note that I'm building this on top of `finto/rad-identities`.
=> rad binaries
