- librad2/src/keys/device.rs
- librad2/src/keys/pgp.rs
We want our device key to not leave the device. What we want to enable, though, is that people use their primary GPG key (published to keyservers) to certify that they own the device key. That is, associate the device key with their identity.
After studying [RFC448](https://tools.ietf.org/html/rfc4880) for a while, I realised that it's quite possible to forego a sequence of arcane GPG commands (with the risk of leaving the device key in they GPG keyring): we simply make them export their (secret) primary key (`gpg --export-secret-keys --armor`), read it in, create a subkey binding, and ouput the armored public parts again. The ouput can be uploaded to keyservers directly.
We may need to think about revocation at some later point.
> PGP certification of device key

- Cargo.lock
- librad/Cargo.toml
- librad/src/lib.rs
- librad/src/meta/common.rs
- librad/src/meta/mod.rs
- librad/src/meta/profile.rs
- librad/src/meta/serde_helpers.rs
- rad2/src/commands/profiles.rs
The sequoia-rfc2822 crate is deprecated[0][1], and some people are even
contemplating yanking it completely from crates.io[2]. We also don't
need full RFC2822-compliance, as we might do funky things with the
domain part.
[0]: https://gitlab.com/sequoia-pgp/sequoia/issues/279
[1]: https://gitlab.com/sequoia-pgp/sequoia/merge_requests/221
[2]: https://gitlab.com/sequoia-pgp/sequoia/issues/376
> Remove dependency on sequoia-rfc2822, and replace with simple datatype

- librad/src/keys/device.rs
- librad/src/meta/common.rs
- librad/src/meta/contributor.rs
- librad/src/meta/mod.rs
- librad/src/meta/profile.rs
- librad/src/meta/project.rs
As @xla [points out](https://github.com/radicle-dev/radicle-link/pull/22#discussion_r359914612), Rust admits multiple versions of the same dependency to be linked into a program. Friends and acquaintances of `java.lang.ClassLoader` will notice that the smartness of presenting this as a solution to "dependency hell" is bounded. In particular, re-exporting from a dependency allows the dependency to break the public API (pinning to a patch version is a non-solution for a library).
Hence, we wrap the `url::Url` type (exposing only the minimally needed functionality for now). Access to underlying `ParseError`s is permitted via the `.cause()` method, although implementing control flow in them is discouraged.
There might be similar cases already introduced, which will be addressed at a later …
> Wrap `Url`

- librad/src/keys/device.rs
- librad/src/meta/project.rs
- librad/src/peer.rs
`dedup` works like the unix shell `uniq` cmd: it needs the vector to be sorted.
> Fixed maintainers dedup.

- .rustfmt.toml
Forgot to enable that when switching to nightly. I draw unreasonable enjoyment
from this weird Rust convention to limit code to 100, but comments to 80
columns.
> fmt: Enable wrap_comments

- librad/src/keys/mod.rs
- librad/src/keys/storage.rs
- rad2/src/commands/keys.rs
- rad2/src/commands/profiles.rs
- rad2/src/commands/project.rs
- rad2/src/config.rs
- rad2/src/main.rs
I got a bit annoyed by the way I set this up the first time, namely that I was
instantiating effectful state (storage, pinentry, ...) ad-hoc everywhere, so I
centralisised that.
There is also now the option to override the (equivalent of) XDG_* root by
setting the RAD_ROOT environment variable or passing --paths (oof feel free to
bikeshed that naming choice).
Additionally, the pinentry (i.e. password prompt) for the keystore is now
threaded as part of the type, and doesn't have to be passed to the methods. This
is a breaking change @xla.
> CLI: Refactor option parsing and effectful state setup

- CODEOWNERS
To save myself a couple of pointing-device movements.
Every PR should now automatically request a review from the radicle-link "core team", and additionally from upstream folks concerned with the proxy. Hope this is useful for folks using email or GH notification filters to highlight attention-worthy things in the flood of incoming patches.
> Set up GH CODEOWNERS feature

- librad/src/paths.rs
I mistakenly assumed `ProjectDirs::from_path` would ignore the platform-dependent
roots (e.g. XDG_* on Linux), but it instead overrides any paths _below_ that.
What we actually want is to be able to store all configuration and state under
a user-defined root directory, which is useful for testing or otherwise
constrained deployments. So this patch fixes that by precomputing things
either in a platform-dependent (`new()`) or user-defined (`from_root`) way.
> Fix `Paths` to ignore platform conventions when being told so

- librad/src/git/transport.rs
- librad/src/net/protocol.rs
- librad/src/net/quic.rs
Previous attempts failed due to poor type inference (see comment of
`impl GitStreamFactory for Protocol`).
> Box away the git transport stream.

- Cargo.lock
- librad/Cargo.toml
- librad/src/id.rs
- librad/src/id/entity.rs
- librad/src/id/entity/data.rs
- librad/src/id/project.rs
- librad/src/id/test.rs
- librad/src/id/uri.rs
- librad/src/id/user.rs
- librad/src/keys/device.rs
I have reimplemented User and Project as type instances of a generic `Entity<T`>, where Entity supports TUF verification using URI resolution where needed.
There is an `EntityData` struct that has two main roles:
* a "builder" pattern intermediate object, and
* an intermediate step for [de]serialization.
This because Entity (and therefore User and Project) are essentially immutable.
They have the invariant that their hash must always be correct, therefore it is not possible to mutate them without either breaking the invariant or recomputing the hash.
The only thing that can be changed are signatures, which can be added with the `sign` function.
This means that the invariants should be checked on deserialization (when passing from EntityData to Entity).
There is a `Resolver` async trait …
> Data structures for identities and verification.

- librad/src/meta/entity.rs
- librad/src/meta/entity_test.rs
Fixes #119 
Added `Verified` when we are exiting the loop for `compute_history_status`. This needed to change the test code slightly, so as not to `clone` the `user` so we could mutate it.
Also added some refactoring code as I was passing through.
> Verify & Testify

- .buildkite/pipeline.yaml
- ci/advisory
- ci/build-test
- ci/clippy
- ci/docs
- ci/run
Fixes #120 
I split the commands out into multiple files. Each one of these, I think, can be run in parallel.
I added a `- wait` for the build and test step because I think this might make sense. We mostly care about building and testing initially, the rest can be done during a cleanup. I think it would also mean we have the build cache set up from the build and test too.
> Parallel Build Checks

- Cargo.lock
- librad/src/keys.rs
- librad/src/lib.rs
- radicle-keystore/Cargo.toml
- radicle-keystore/src/crypto.rs
- radicle-keystore/src/memory.rs
We initialise `sodiumoxide` lazily. This eliminates the need to initialise
`librad` explicitly (which is easy to forget, and awkward to enforce on the
type level).
The choice of using `lazy_static` avoids memory barriers incurred by either
calling `sodiumoxide::init()` repeatedly, or using `std::sync::Once`.
On top of #137 for merging convenience (renames made there).
> Eliminate explicit library  init

- librad/examples/mesh.rs
- librad/src/git.rs
- librad/src/git/repo.rs
- librad/src/meta/entity.rs
- librad/src/meta/entity/data.rs
- librad/src/meta/entity_test.rs
- librad/src/meta/project.rs
- librad/src/meta/user.rs
- librad/src/net/peer.rs
- librad/src/project.rs
- librad/tests/propagation_basic.rs
I took the liberty of testing out using `PhantomData` on `Entity`. I think the changes are pretty cool since you can't push an `Entity<T, Unknown>` onto `UserHistory` -- yay type safety!
I removed the `VerificationStatus` from `Entity` because now the types tell you when things were successful, otherwise, you got an error.
I hope it's ok that I went and did this :bow: My curiosity was piqued :grin:
> Phantom Status

- Cargo.lock
- librad/Cargo.toml
- librad/src/net/gossip/storage.rs
- librad/src/net/peer.rs
- librad/tests/propagation_basic.rs
Introduce an upstream event channel for `net::Peer`.
Allows to subscribe to "background" activity triggered by gossip. Note that running the tests multithreaded is still flaky, so there might be some other issue.
On top of #149
> Peer events

- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/meta/entity.rs
- librad/src/meta/entity/data.rs
- librad/src/meta/entity_test.rs
- librad/src/meta/project.rs
- librad/src/meta/user.rs
- librad/src/net/peer.rs
- librad/tests/fixtures.rs
- librad/tests/propagation_basic.rs
This is a first step towards the goal.
The feature is implemented but there are still the following issues:
* The code only uses the "unknown" state: verification calls would need a proper resolver so i would do this in another pull request, after we have resolvers in place.
* I would add some type aliases like `DraftUser`, `SignedUser` and `VerifiedUser` but I wanted to agree on naming first.
* A couple of clippy issues with `new` method names.
* The API does not consume the unverified entity, it still sets its status but it also produces a new (cloned) entity of the proper type; we should talk more about how error handling would work with a consuming API.
> Entity status with type witnesses

- Cargo.lock
- librad/Cargo.toml
- librad/src/git/repo.rs
Depends on https://github.com/radicle-dev/radicle-surf/pull/112
Bumps the surf revision so that proxy can make use of the latest changes. Also link can now use the `RepositoryRef` version of the `Browser`.
> Bump and fix surf revision

- librad/src/git/ext.rs
- librad/src/git/storage.rs
While integrating `librad` into `proxy`, I was running into an issue where tracking was attempted to be done twice on an entity. Presumably, it's because we insert the user first, then create a project with that user. But not 100% sure about this.
Either way, it seems useful for tracking to idempotent and not scream when we try to track the same peer twice.
> Idempotent Track

- librad/src/git/storage.rs
Fixes #160 
When trying to `open` the `Storage`, if it wasn't found we call `init` for setting it up.
> Open or Init

- librad/src/git/storage.rs
- librad/src/meta/entity.rs
- librad/src/meta/entity/data.rs
- librad/src/meta/entity_test.rs
- librad/src/meta/project.rs
- librad/src/meta/user.rs
The idea is to approach the problem in layers.
The lowest layer is about finding the refs (commits) that point to entity metadata branches.
This is the 1st commit here.
Then I'd build machinery that given a commit extracts a "stream" of blobs out of it (which should be the raw data of the entity revisions).
This is an upcoming commit.
At that point we can deserialize the entities out of those blobs to get a real resolver, and at that point we can add the verification process into the mix...
> Get entities out of the monorepo

- librad/src/net/connection.rs
- librad/src/net/gossip.rs
- librad/src/net/gossip/types.rs
- librad/src/net/peer.rs
- librad/src/net/protocol.rs
Tracking ports will only become relevant after #66 (hole punching), and are plain wrong currently.
> Gossip only `IpAddr`s, not `SocketAddr`s

- librad/src/net/peer.rs
Otherwise, pretend we've already seen it -- which just means to stop propagating the gossip here. We know at this point that the provider either lied, or the ref was already gone before we could fetch it. In either case, and since there was no error, noone else should be able to get the data from the provider either. And since we don't have it, neither from us.
> Check if a fetch triggered by gossip actually applied the value

- radicle-keystore/src/lib.rs
I missed this in the previous PR.
> Re-export SecStr since it's in the SecretKeyExt interface

- librad/src/git/ext/blob.rs
- librad/src/git/ext/error.rs
- librad/src/git/ext/oid.rs
- librad/src/git/ext/reference.rs
- librad/src/git/ext/revwalk.rs
- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
- librad/src/git/types.rs
- librad/src/test.rs
In a desperate attempt to stay on top of the recent outbreak of productivity, and to minimise the amount of merge conflicts, I am:
* Splitting up "utitility" things into (a lot of) separate modules
* Imposing my own naming preferences
* Reducing some duplication
> Split git-related things into modules + add more test utils

- librad/src/net/peer.rs
This makes it more convenient for library users to defer polling the run loop
future, and storing it in a struct meanwhile.
> Return run loop box instead of opaque type

- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
- librad/src/lib.rs
- librad/src/net/peer.rs
- librad/tests/propagation_basic.rs
- librad/tests/testnet.rs
Fixes #196
---
First step towards using radicle-dev/radicle-keystore#1, instead of passing around the secret key. On top of #197
> Pass secret key to storage only where needed

- Cargo.lock
- deny.toml
- librad/Cargo.toml
- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/lib.rs
This may be _controversial_, but I was thinking we could just remove surf altogether. `Storage` has an `AsRef<git::Repository>` impl so we can create a `Browser` by getting the ref, and then build the `Namespace` from the `RadUrn`'s `id`.
i.e.
```rust
let namespace = Namespace::from(urn.id.to_string());
let browser = Broswer::new_with_namespace(storage.as_ref(), &namespace, default_branch)?;
```
This means that we'll never get any mismatch between the `Browser` `librad` will given back and the `Browser` by the version provided by crates in upstream code.
If this doesn't suit, I can opt for the version bound route instead.
> Remove Surf

- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
Allow us to retrieve the rad/self for some RadUrn (and PeerId) in our Storage.
For Repo it delegates to the Storage passing its own RadUrn.
> Add get for rad/self

- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
- librad/src/meta/entity.rs
The `urn` method on `Entity` was using `hash` instead of `root_hash`. This means that are `RadUrn`'s weren't stable and the repository was not in the correct format. It would result in a lone `namespace/<id>` with just `rad/refs` while the entity's `rad/id` would live in another `namespace/<id>`.
This PR fixes this issue and adds a test case to ensure that we have each of those refs under the `namespace` for each repo we create.
> Fix RadUrn

- librad/src/paths.rs
Naming of the environment variable, as well as the general XDG scheme, will
need to be revisited for robustness between different radicle applications.
> Enable construction of `Paths` from a root set via the environment

- Cargo.lock
- Cargo.toml
- git-helpers/Cargo.toml
- git-helpers/src/bin/remote/main.rs
- git-helpers/src/credential.rs
- git-helpers/src/lib.rs
- git-helpers/tests/remote.rs
- librad/Cargo.toml
Builds on top of the local transport, allowing interaction with the storage
backend via the git CLI. Noteworthy is the use of git's credential helper
infrastructure to prompt for the keystore passphrase.
Note that it is not yet clear how to set HEAD (the default branch) for the
logical repository, rendering the clone without a checked-out working copy.
Configuring the remote tracking branches as actual remotes in the work tree is
not part of this patch either.
> Git remote helper

- git-helpers/tests/remote.rs
- librad-test/src/lib.rs
- librad-test/src/rad/entity.rs
- librad-test/src/rad/resolver.rs
- librad/src/git/storage/config.rs
- librad/src/git/storage/test.rs
- librad/src/meta/entity.rs
- librad/src/meta/entity_test.rs
- librad/src/test.rs
- librad/tests/propagation_basic.rs
The `Resolver` trait for getting entities from URNs has been defined as async but the whole libgit2 API is not async.
Entity resolution at this level is not expected to use the network, only to read data from the git monorepo (through a `Storage` instance) with eventual help from a cache.
Since the whole `Storage` API is not async, making entity `Resolver`s async adds complexity for no technical reason.
If or when interaction with `Storage` will become async entity resolution will follow the same path using the same approach (it is expected to be part of the `Storage` API anyway).
> Made entity resolvers synchronous.

- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/git/storage/fetch.rs
- librad/src/git/types.rs
Adding functions to retrieve the `refs/heads/*` references that would
live under a RadUrn for our local peer view and a remote peer view.
Fixes #239
> Add refs_heads functions

- librad/src/net/gossip.rs
- librad/src/net/protocol.rs
Fixes #252 
When we query the network for some `A` we get back a stream of `Has of
A`. We never checked that it indeed was the `A` we wanted. This change
introduces the check to see if they're equal.
> Check Has is what we Want

- librad/src/git/storage/fetch.rs
We do not actually need it, and it may cause a segfault in libgit2 when a custom
transport is used and the URL contains a port number. Also, make fetch tracing
more legible.
> Don't update FETCH_HEAD when fetching

- librad/src/git/p2p/url.rs
- librad/src/git/storage.rs
When candidate network addresses of a remote peer are known, we can pass them
through libgit2 as a hint for the p2p layer to establish a connection if none
already exists.
> Address hints for GitUrl

- default.nix
- librad/src/git/storage/fetch.rs
- librad/src/git/types.rs
It's useful to have a way of constructing a Refspec from two of the same
References. It makes it re-usable to any consumers in case they need to
create these specs themselves.
Above the table: I don't want to repeat this logic in Upstream just so I can have a safe way of setting up a remote :upside_down_face:
> Add refspec constructors

- librad/src/git/storage.rs
- librad/src/git/storage/fetch.rs
- librad/src/git/storage/test.rs
- librad/src/git/types.rs
- librad/src/git/types/existential.rs
- librad/src/git/types/reference.rs
We had no way of talking about references that live under `refs/heads` or
`refs/remotes`. This is useful for setting up remote fetch/push specs.
I chose a separate type rather than trying to shoe-horn it into the
existing model.
> Add BranchRef

- Cargo.lock
- librad-test/src/rad/testnet.rs
- librad/Cargo.toml
- librad/src/git/p2p/transport.rs
- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/net/gossip.rs
- librad/src/net/peer.rs
- librad/src/net/protocol.rs
- librad/tests/propagation_basic.rs
I ended up treating this as a proper connect, ie. add the connection to the pool, and start gossiping, because of the following:
Due to a bug in either `libgit2` or `git2-rs`, or just the way the Rust FFI works, we can't register our transport as "stateful". This means that `libgit2` will always try to open _two_ connections, one for the refs advertisement, and another one for getting the packfile. Always helpful, it will also call `close()` on our transport, so there isn't a way to know when it's done.
Although we don't incur a full TLS handshake thanks to session tickets, the connection establishment is still roughly equivalent to a TCP handshake.
Otoh, it is also semantically _correct_ to keep being connected, because if we got what we wanted from the peer, we are also interested in …
> Use address hints to establish (git) connections if applicable

- librad/src/git/types.rs
- librad/src/git/types/remote.rs
Working on top of #270 
Add a way of setting up a rad remote to the monorepo, setting it up with
any push specs specified and the single fetch spec.
This utilises a trait to turn Refspecs into Strings, so we can have
multiple in a Vec without worrying about their types lining up.
> Add Remote struct

- Cargo.lock
- Cargo.toml
- deny.toml
- librad/Cargo.toml
- librad/src/net/quic.rs
This gives us rustls 0.18 with ed25519 support, and removes the need for consumers to apply the cargo patch.
Supersedes #242 
---
Nb.: `upstream` **must** remove the `patch`, actually. I'm trying to get a `cargo update` against `upstream/proxy` going, but getting a lot of unrelated compile errors. /cc @xla
> Bump quinn

- librad/src/git/types.rs
- librad/src/git/types/existential.rs
- librad/src/git/types/reference.rs
- librad/src/git/types/remote.rs
Fixes #269 
In our quest for MORE POLYMORPHISM, we move the refspec constructor of
two references into the polymorphic methods of Reference. We also allow
the remotes to change in a Refspec.
This means that we can pass in a Reference with a different Namespace
and Remote, and get back the Refspec for it.
The bonus is that the equality of the Cardinality of the two References is
enforced by the ReferenceInfo trait.
> Polymorphic refspec constructor

- Cargo.lock
- git-helpers/Cargo.toml
- librad/Cargo.toml
Catch up with radicle-dev/radicle-keystore#6.
> Bump keystore dependency

- Cargo.lock
- librad/Cargo.toml
- librad/src/git.rs
- librad/src/git/trailer.rs
`DRAFT`
Addresses #267 
* **Parse trailers**
Given a `&str`, return an iterator of `(String, String)` pairs, such that:
including newlines), and does not itself contain empty lines (but it may
contain newline characters)
> Parse git commit message trailers

- git-helpers/tests/remote.rs
- librad/src/git/local/transport.rs
- librad/src/git/local/url.rs
- librad/src/git/types/remote.rs
- librad/src/signer.rs
- librad/tests/propagation_basic.rs
The local transport was using a global mutex on `Option<Settings>`. In
concurrent runs tests would end up overwriting each other's version of
this mutex and would end up in inconsistent states.
To solve this we need to separate test case's runs. Initially, we
attempted to use another lock `Mutex<()>` and have a bracketed runner,
which would lock, fill the `Option<Settings>`, run the action, and clean
up & release the lock. This still ended up in race conditions.
This solution uses a HashMap from PeerId to Settings. This works since
we expect individual runs to have separate PeerIds. The consequence of
this is that we need a way to look up the Settings when running the git
action. We encode this in the LocalUrl, so we add the PeerId as the
username of the Url that's passed.
> Use a HashMap for shared Settings ref

- Cargo.lock
- librad/tests/propagation_basic.rs
For demonstration purposes, mainly.
Unfortunately, I can't see a way to intercept `git-receive-pack` in such a way
that we could get at the pushed refs -- otherwise, the local transport could
handle to gossiping.
Also, async/await raises its ugly head again.
> Fire gossip announcement from git remote callback in e2e test

- librad/src/git/storage.rs
- librad/tests/propagation_basic.rs
Directly fixes https://github.com/radicle-dev/radicle-link/issues/250, may be a part of the wider discussion in https://github.com/radicle-dev/radicle-link/issues/266.
Diving into `libgit2` codebase sure was an interesting experience :laughing:
> Fix all_metadata returning remote entities

- librad/src/git/ext/blob.rs
- librad/src/git/ext/oid.rs
- librad/src/git/header.rs
- librad/src/git/local/transport.rs
- librad/src/git/local/url.rs
- librad/src/git/p2p/url.rs
- librad/src/git/refs.rs
- librad/src/git/storage.rs
- librad/src/git/storage/config.rs
- librad/src/git/trailer.rs
- librad/src/hash.rs
- librad/src/identities/payload.rs
- librad/src/identities/urn.rs
- librad/src/keys.rs
- librad/src/meta/common.rs
- librad/src/meta/entity.rs
- librad/src/net/gossip/error.rs
- librad/src/net/peer.rs
- librad/src/net/protocol.rs
- librad/src/net/quic.rs
- librad/src/net/upgrade.rs
- librad/src/peer.rs
- librad/src/uri.rs
- radicle-tracker/src/thread.rs
Closes #273 
To follow the Radicle convention regarding error messages [0]. Here we
only concern with ensuring the error messages start with a lowercase
character.
[0]: https://github.com/radicle-dev/radicle-decisions/pull/3
> Lowercase all error messages

- librad/src/uri.rs
This change is for convenience of downstream dependencies.
> Derive de/serialize on uri::Path

- librad/src/git.rs
- librad/src/git/include.rs
- librad/src/git/local/transport.rs
- librad/src/git/types/remote.rs
- librad/tests/working_copy.rs
Fixes #287 
Adds utilities to create an include file that has a list of remotes. This will allow upstream users to generate include files for their working directories to keep track of remotes.
> Include Utilities

- Cargo.lock
- librad/Cargo.toml
- librad/src/identities/generic/gen.rs
- librad/src/identities/payload.rs
- librad/src/internal/canonical.rs
Derive macros somehow interfere with typechecker error reporting, for
some reason even when the type being impl'd is not related at all.
`proptest_derive::Arbitrary` is the worst offender, although `serde`
derive macros leak as well.
Henceforth, macros shallt generally be frowned upon in this library, an
`proptest_derive` permanently banned.
> Derive all Arbitrary impls by hand

- librad/src/net/peer.rs
- librad/tests/propagation_basic.rs
- seed/src/lib.rs
It does not make sense to poll the responses stream for more than a
couple of seconds.
> PeerApi: Require timeout for providers query

- Cargo.lock
- librad/Cargo.toml
- librad/src/identities.rs
- librad/src/identities/delegation.rs
- librad/src/identities/delegation/direct.rs
- librad/src/identities/delegation/indirect.rs
- librad/src/identities/generic.rs
- librad/src/identities/generic/error.rs
- librad/src/identities/generic/gen.rs
- librad/src/identities/generic/tests.rs
- librad/src/identities/payload.rs
- librad/src/identities/sealed.rs
- librad/src/identities/sign.rs
- librad/src/identities/sign/error.rs
- librad/src/internal/canonical.rs
Aims to define all git-independent aspects of the identities system
generically, such that we can reason about it sans IO. The respective
modules are not part of the surface API of `librad`, and may later be
hidden (modulo `rustdoc` rendering).
> Identities: generic types and verification

- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
Added tests to confirm the setting of default rad/self and checking if a URN exists when calling `create_repo` twice. Turns out there was a bug in the latter so I'm including the fix.
> Storage Tests

- librad/src/paths.rs
To support work in radicle-dev/radicle-upstream#894 while leaving the
possibility to use the same generated includes in a possible rad cli
this change adds a new path that can be used to store include files
scope to projects in the monorepo.
> Add includes paths

- librad/src/paths.rs
As a follow-up to #329  and a more convenient way to get the underlying
`&Path` than using `all_dirs`.
> Add method to paths for git includes

- librad/src/git/include.rs
- librad/tests/working_copy.rs
Commonly in tandem to the generation of the include file itself, working
copies need to be equipped with an include directive pointing to said
files. To avoid miss-spellings in the config key this change exports
a helper for that.
> Add helper to set include directive

- Cargo.lock
- librad/Cargo.toml
Funnily enough, I noticed both the source and the released version being built.
Maybe this combo of version + branch + git is a bit, errm, non-deterministic?
> Bump ed25519-zebra to released version (2.2.0)

- librad-test/src/git.rs
- librad-test/src/lib.rs
- librad/src/git/storage/fetch.rs
- librad/src/git/types.rs
- librad/tests/propagation_basic.rs
- librad/tests/working_copy.rs
We add a test that does the following:
* Peer 1 creates a project
* Peer 1 makes a commit to their default branch
* Peer 2 clones from Peer 1
* Peer 3 clones from Peer 2
The expectation is that Peer 2 has Peer 1's `heads/*`, which it does.
It is also expected that Peer 3 has Peer 1's `heads/*`, which it doesn't.
> Menage a troi

- librad/src/net/gossip.rs
We can't connect to ourselves, so there is no point in remembering. This
invariant should probably be maintained by the `KnownPeers` datastructure,
but this will do as a quick fix.
> Gossip: Quick fix to not remember local peer as "known"

- ci/build-test
Strangely, `cargo` can be told to run only the unit or doc tests, but not to
only run the integration tests. Perhaps we should meditate over organising those
slow tests in a different way to work around the deficiencies of the tooling
(see also #353).
> CI: Run tests verbosely

- git-helpers/tests/remote.rs
- librad-test/src/rad/testnet.rs
- librad/src/git/include.rs
- librad/src/git/p2p/transport.rs
- librad/src/git/p2p/url.rs
- librad/src/git/refs.rs
- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/git/storage/fetch.rs
- librad/src/git/storage/test.rs
- librad/src/git/types.rs
- librad/src/git/types/remote.rs
- librad/src/identities/delegation/indirect.rs
- librad/src/identities/generic/gen.rs
- librad/src/identities/payload.rs
- librad/src/keys.rs
- librad/src/lib.rs
- librad/src/net/connection.rs
- librad/src/net/gossip.rs
- librad/src/net/gossip/storage.rs
- librad/src/net/peer.rs
- librad/src/net/protocol.rs
- librad/src/net/quic.rs
- librad/src/net/upgrade.rs
- librad/src/peer.rs
- librad/src/uri.rs
- librad/tests/propagation_basic.rs
- librad/tests/working_copy.rs
- seed/src/lib.rs
Fixes #348
Supersedes #362 
We derive Copy for PublicKey & PeerId since they're simply a slice of
bytes.
The majority of the changes are removing the clone calls on
PeerId/PublickKey and removing the ask by reference on PeerId in
function calls.
> Make PublicKey & PeerId Copy

- librad/src/git/types.rs
The _namespace field on Reference is hidden because a FlatRef has the
field set a PhantomData. This information is useful for NamespacedRef,
on the other hand. So this provides a method on NamespacedRef for a
caller to get the Namespace.
> NamespacedRef::namespace

- librad/src/git/repo.rs
- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
If we call untrack on a non-existing remote we get an error back from
git2 saying that it doesn't exist. It would make more sense to match on
the remote not existing and return a bool whether the remote used to
exist or not.
> Allow untrack of non-existing remote

- librad/src/git/local/transport.rs
- librad/tests/propagation_basic.rs
- librad/tests/working_copy.rs
`libgit2` may drop all references to the local transport before the
child process exited. We must, however, `wait(2)` on the children on a
(non-cancellable) thread, which leads to the dilemma of either risking
to block the parent process (by joining on this thread), or exiting it
prematurely.
We thus establish a side-band channel which allows non-longrunning
processes to fully await completion of their local transport operations
(e.g. in a `Drop` finaliser).
---
Supersedes #375
Note: one might think that it would be possible to simply use a `std::sync::mpsc`
channel for this, but that is not the case due to caught panics not being `Sync`.
> Local transport: side-channel for blocking on local transport results

- librad/src/git/storage.rs
Somewhat counter-intuitively, `Force::False` will still return an error
if the symbolic reference already exists. We ignore this error, and
proceed attempting to symref the remaining certifier ids.
> Fix: ignore errors if certifier symref already exists

- librad/src/net/protocol.rs
- seed/src/lib.rs
Adds explicit disconnect handling in the two places where they seemed to
lack so far. This should make it possible for a protocol user to observe
all disconnections, not only the ones initiated by the gossip layer.
Might be worthwhile at a later stage to bubble up the connect and
disconnect control events from gossip. Also aligned the variant names.
> protocol: handle disconnect when conn is done

- macros/src/lib.rs
Turns out we can actually avoid the runtime conversion (and allocation).
The only potential drawback is that we emit `unsafe` code, which linters
may dislike.
> Macros: transmute into target type

- librad/src/git/refs.rs
- librad/src/git/storage.rs
- librad/src/git/storage/test.rs
Such that serde sees it as a JSON object, which allows for better
evolvability in the future.
> Terminate remotes graph with a map

- librad/src/git/fetch.rs
- librad/src/git/refs.rs
A forward patch of https://github.com/radicle-dev/radicle-link/pull/406
Using a HashSet the iter method will return items in an arbitrary order.
Since this is what serde uses under the hood to turn HashSet into an
array, it destabilises the signing and verification of refs.
Using a BTreeSet gives us a guaranteed order for the array, meaning
consistent de/serialization across peers.
> Use BTreeSet instead of HashSet

- librad/src/git/include.rs
- librad/src/git/types/remote.rs
- librad/tests/working_copy.rs
maint patch: https://github.com/radicle-dev/radicle-link/pull/412
If no fetch refspec was provided we would incorrectly use our own PeerId
in the refspec. This is essentially useless because we shouldn't have
our own PeerId under our remotes.
Instead, we change the interface so that remotes are added by providing
the PeerId and handle, then building the Remote with the fetch refspec
internally.
> Forward patch: Include fixes

- librad/src/git/include.rs
- librad/src/git/types/remote.rs
- librad/tests/working_copy.rs
Fixes #414 
I'm not gonna backwards patch this because it's not critical.
> Use RefLike for Remote.name

- librad/src/git.rs
- librad/src/git/storage.rs
Should help prevent exhausting fd limits, as libgit2 is accumulating fds to packfiles.
> git: set libgit2 mwindow file limit

- librad/src/net/gossip.rs
- librad/src/net/protocol.rs
The idea to eject previous connections from a remote peer is racy, as described in #431. Instead, we reject new incoming connections until the old one is either closed gracefully, or times out.
> protocol: reject duplicate connections

- librad/src/lib.rs
- librad/src/net/protocol.rs
The advertised address might be `0.0.0.0`. This is a quick fix, we may want to catch this earlier in the future.
> protocol: filter out unroutable IP addresses for connect

- librad/src/git/replication.rs
- librad/src/net/protocol.rs
- librad/src/net/quic.rs
- replication: do not track self
- replication: deny replicating from self
- net: deny ingress + egress connections to local peer id
Does NOT fix #410, but can't hurt either.
> Various guards against dancing with oneself

- librad/src/net/gossip.rs
- librad/src/net/protocol.rs
The idea to eject previous connections from a remote peer is racy, as
described in #431. Instead, we reject new incoming connections until the
old one is either closed gracefully, or times out.
This also entails to not automatically terminate connections when a peer
is ejected from the active set of gossip membership.
> forward-port: protocol: reject duplicate connections (#434)

- librad/src/net/gossip.rs
- librad/src/net/protocol.rs
It is unclear if there is a condition where `seen_addrs` can be empty,
or if `quinn::Connection::remote_address` can return a non-routable
address. This is a quick fix to to prevent `future::select_ok` from
panicking when given an empty iterator.
> net: guard against a panic when connecting

- librad/src/git/include.rs
Should fix [radicle-upstream/issues/1389](https://github.com/radicle-dev/radicle-upstream/issues/1389)
> Include peer id suffix in refspecs

- librad/src/git/storage.rs
- librad/src/net/peer/storage.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/broadcast.rs
- librad/src/net/protocol/broadcast/storage.rs
- librad/src/net/protocol/gossip.rs
- librad/src/net/protocol/info.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/tick.rs
Instead of passing the peer id of the sender, we need to pass the origin, which
preserves relaying semantics. This also means that we actually have address
hints available.
> Fix broadcast local storage provider

- librad-test/src/rad/testnet.rs
- librad/src/net.rs
- librad/src/net/protocol.rs
- librad/src/net/quic.rs
- librad/src/net/quic/endpoint.rs
- seed/src/lib.rs
For operating "devnets" without physical network isolation.
Also, spell out the protocol versioning policy, and bump the version as
`net/next` is incompatible.
> net: permit logical network identifiers in ALPN

- librad-test/src/rad/testnet.rs
- librad/src/net.rs
- librad/src/net/peer.rs
- librad/src/net/quic.rs
- seed/src/lib.rs
Backport of #487 (4e8995823171b364bba67f0b91832812f0d538cb) to `next`.
> backport: net: permit logical network identifiers in ALPN

- librad/src/net/quic/stream.rs
Not exactly sure why that is, but otherwise the network will become
disconnected after about 10min due to collecting idle connections
(detected via #493).
> net: tickle connection in AsyncWrite::poll_close

- git-helpers/src/remote_helper.rs
- git-helpers/tests/remote.rs
- librad/Cargo.toml
- librad/src/lib.rs
- librad/src/paths.rs
- librad/src/profile.rs
- seed/src/lib.rs
To address #488 we add the `Profile` struct.
This pull request is against `next`. I will try to write automatic migration code for this so we can include it in `maint` without a breaking change.
We’ve also simplified some methods on `Paths` and made them private.
> Add profiles and profile-scoped paths

- librad/Cargo.toml
0.1.12 breaks our builds at the moment so we should specify an upper
bound of 0.1.11.
See: https://github.com/tokio-rs/tracing/issues/1227
Feel free to fix/merge while I'm out next week :smile:
> tracing-attributes version bound

- ci/build-test
- e2e/Cargo.toml
- e2e/src/bin/ephemeral-peer.rs
- librad-test/Cargo.toml
- librad-test/src/rad/testnet.rs
- librad/Cargo.toml
- librad/src/git/p2p/server.rs
- librad/src/net/protocol.rs
- librad/tests/scenario/collaboration.rs
- librad/tests/scenario/menage.rs
- librad/tests/scenario/working_copy.rs
- librad/tests/smoke/gossip.rs
- seed/Cargo.toml
- seed/src/lib.rs
Leaving this as draft until `next`, `net/next` all converged on a single trunk.
> Tokio EINS

- librad/src/net/peer.rs
- seed/src/event.rs
While testing the `radicle-bins` code on the `seed-next` branch I spotted some issues.
The details of the fixes are in the commit messages.
I'll probably keep this open while I possibly find anything else that can be improved.
> Fixes found while testing seed

- librad/Cargo.toml
Since there was a release of tracing-attributes
(https://crates.io/crates/tracing-attributes/0.1.13) we can place a
better range on the versions that is lower than 0.1.12 and anything
upwards of 0.1.13, inclusive.
> Update Cargo.toml: tracing-attributes

- librad/src/git/fetch.rs
- librad/src/git/refs.rs
- librad/src/git/replication.rs
- librad/src/net/quic/connection.rs
- librad/src/net/quic/stream.rs
Fixes a few instances of URNs going through Debug instead of Display for
logging. This is still not ideal, because composite values are often
better logged through Debug, but then the URN field is somewhat less
useful again. Need to investigate with upstream why the Value trait is
sealed.
Also improves the span reporting when a stream error occurs.
> instrumentation: stream error span + URN display

- librad/src/git/storage.rs
- librad/src/git/storage/pool.rs
- librad/src/net/peer/storage.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/error.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/tick.rs
It turns out we will need access to a `git::Storage` from some stream
handlers, specifically in pooled form due to `Send`/`Sync` requirements.
As we need to pull that out from a larger structure (respectively
wrappers), a trait is in order. Since we need to thread the constraint
through the various IO function, we defined a composite trait to make
constraint signatures shorter.
> git, net: Add a "capability" trait to mark pooled storage

- .github/workflows/fast.yaml
- ci/test-fast
Adds a GitHüb workflow running a minimal set of lints + tests on
proprietary platforms. Additionally, this "fast set" is run for pull
requests from other repositories, so that we can disable running the
(slow) builds for externals on our hardware.
> ci: Add Hüb workflow

- librad/src/net/protocol.rs
- librad/src/net/protocol/membership/hpv.rs
- librad/src/net/protocol/membership/partial_view.rs
Gossip messages must only be accepted from peers in the partial view, as
otherwise it would be too easy to flood the network with random
messages, amplified by faithful peers. However, requiring active set
membership is too strict, as promotion / demotion is not synchronised.
Instead, we check for partial view inclusion regardless of status.
> net: Relax membership check before discarding gossip as unsolicited

- librad/src/net/protocol/membership/tick.rs
When a peer is demoted from the active view, the other end needs to be
notified of that. This was not the case, because past self outsmarted
himself.
Note that this does not invalidate #542, as gossip could be in-flight
before the `Disconnect` arrives.
> net: Fix `Disconnect` not being sent on demotion

- librad/src/net/peer.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/event.rs
- librad/src/net/protocol/membership/hpv.rs
- seed/src/handle.rs
- seed/src/lib.rs
To get an understanding where in the partial view a certain peer is the
protocol can be phoned now to return the list of active, known and
passive peers.
> protocol: expose memebership lists via tincan

- git-helpers/src/remote_helper.rs
This pull-request apply the suggestion of #471 and adds a more informative message when `git-remote-rad` is ran from the command line directly.
The error message is now
```
Error: This remote helper is transparently used by Git when you use commands
such as "git fetch <URL>", "git clone <URL>", "git push <URL>" or
"git remote add <nick> <URL>", where <URL> begins with "rad://".
See https://git-scm.com/docs/git-remote-ext for more detail.
``` 
instead of
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /cache/cargo/git/checkouts/radicle-link-009c17032bc5eda9/308d2dd/git-helpers/src/remote_helper.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Closes #471
> git-helpers: Add informative git-remote-rad error message

- librad/src/git/identities/person.rs
- librad/src/git/identities/project.rs
- librad/src/identities/git.rs
We add `root` functions for the `Person` and `Project` documents. This
allows us to have a top-level function that will give us the expected
`Urn` for the given payload and delegates.
> git::identities: add root functions

- librad/src/git/identities/any.rs
- librad/src/git/identities/error.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/control.rs
Sometimes it is useful to only list the top-level URNs without accessing
any objects. `list` can then be implemented in terms of `list_urn` +
storage access.
> identities: Split list into `list` and `list_urns`

- librad/src/git/identities/any.rs
- librad/src/git/identities/error.rs
- librad/src/git/replication.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/control.rs
This will help reasoning about what actually happened: we expect certain
refs to be updated during `replicate`, but we couldn't tell before if
they were. Also, no information about any updated "user branches" was
propagated.
> git: Thread through the updated tips when `replicate`-ing

- librad/src/git/identities/any.rs
- librad/src/git/identities/error.rs
- librad/src/git/replication.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/control.rs
- librad/src/net/protocol/error.rs
- librad/src/net/protocol/error/internal.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/io/codec.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/recv.rs
- librad/src/net/protocol/io/recv/gossip.rs
- librad/src/net/protocol/io/recv/membership.rs
- librad/src/net/protocol/io/send.rs
- librad/src/net/protocol/io/send/rpc.rs
- librad/src/net/protocol/io/streams.rs
- librad/src/net/protocol/tick.rs
Possibly good to split out into its own crate soon, to avoid unwieldy
visibility management.
Also note that the receive loop now propagates panics, but that's only a
small bandaid (see #505).
> net: Explode protocol::io module

- librad/src/git/replication.rs
- librad/tests/scenario/menage.rs
We can't build a fetchspec that says `remote/*/rad/ids/*`. So once we've
fetched all remotes we make a second fetch call using `Peek` to get all
the `rad/ids/*` for all those remotes.
We confirm this works by extending the menage test to check for the
peer's `rad/ids` reference exists.
> replication: fetch rad/ids for remotes

- seed/src/lib.rs
Propagates that seed replicated a new peer for an existing `Urn`. We can likely consider removing this post-grafting/NAT'ing
> seed: announce after track

- librad/src/net/protocol.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/recv.rs
- librad/src/net/protocol/io/recv/membership.rs
- librad/src/net/protocol/io/streams.rs
- librad/src/net/protocol/membership/hpv.rs
- librad/src/net/quic.rs
- librad/src/net/quic/connection.rs
- librad/src/net/quic/endpoint.rs
When switching from long-lived bidi- to ad-hoc uni-streams for gossip,
it was not properly considered that the partial view will not repair
itself in mostly-idle networks -- when there's nothing to send, and
nothing received, we need a cue from the connection driver and dispatch
that to the membership state machine. Note that this relies on PTO
expiration respectively delivery of CONNECTION_CLOSE frames from the
remote, and thus doesn't address any weird states due to "unclean"
reconnects within the PTO period.
Related-to: #575
> net: advance membership on connection errors

- librad/src/git/storage.rs
- librad/src/net/peer/storage.rs
- librad/tests/smoke/gossip.rs
The use of `find_commit` meant that we were ignoring tag objects. This
patch uses `find_object` instead to check if we have `Commit` or `Tag`
and then confirms if the SHA is in the given reference.
We extend the gossip test to see if the gossip of the tag gets propagated
back to `peer1`.
> storage: check for tags in has_commit

- librad/src/git/fetch.rs
- librad/tests/smoke/clone.rs
Up until fetches would go through even if the project doesn't exist on
the server. Due to the use of pruning during the fetch this would leave
remotes in a broken state with a tree looking like:
```
└── hyygmx7fm9zaneg64d7gjuohwwmo1obduwk4s6jku3yau9k8y3dgjs
├── heads
│   └── main
└── rad
└── ids
```
> replication: Prevent fetch of non-existing repo 

- .buildkite/pipeline.yaml
- .github/workflows/fast.yaml
Found the right incantations to skip build steps on the two CI services,
depending on whether a PR is from a fork or not.
Note that the "required checks" feature doesn't support conditionals, so
becomes meaningless. That should be okay, though, as Teh Green Button is
verboten anyways.
> ci: fix conditionals for jobs to be skipped

- deny.toml
- librad/Cargo.toml
- librad/src/identities.rs
- librad/src/net/peer.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/cache.rs
- librad/src/net/protocol/control.rs
- librad/src/net/protocol/error.rs
- librad/src/net/protocol/error/internal.rs
- librad/src/net/protocol/event.rs
- librad/src/net/protocol/interrogation.rs
- librad/src/net/protocol/interrogation/rpc.rs
- librad/src/net/protocol/interrogation/xor.rs
- librad/src/net/protocol/io/graft.rs
- librad/src/net/protocol/io/recv.rs
- librad/src/net/protocol/io/recv/interrogation.rs
- librad/src/net/protocol/io/send.rs
- librad/src/net/protocol/io/send/request_response.rs
- librad/src/net/protocol/io/send/rpc.rs
- librad/src/net/protocol/io/streams.rs
- librad/src/net/protocol/tincans.rs
- librad/src/net/upgrade.rs
- librad/tests/smoke/interrogation.rs
In the second installment towards the grafting protocol, we introduce an
API and associated stream type to interrogate a known remote peer about
certain data. Of relevance for grafting is strictly speaking only the
RPC to ask for the complete list of URNs.
We use the Xor filter probabilistic datastructure for that, in order to
gain compact and bounded responses (see commentary inline). The work to
compute the set intersection will be on the requester, while the
responder recomputes the filter only when necessary (morally; we can't
currently intercept refs updates in the relevant places, so recompute
after an expiry timeout).
> net: Interrogation API (grafting pt. 2)

- librad/src/identities/delegation/direct.rs
- librad/src/identities/delegation/indirect.rs
- librad/src/identities/generic.rs
Fixes the previous attempt of requiring the quorum threshold to be at
least 1, which would still require this check. Perhaps a future patch
should reject empty delegations at parse time.
> identities: ensure (eligible) delegations cannot be empty

- librad/src/git/replication.rs
Don't swallow to give more context when fetch and sign errors occur.
> replication: Surface errors

- Cargo.toml
- data/Cargo.toml
- data/README.md
- data/src/lib.rs
- data/src/nonempty.rs
- librad/src/net/quic/connection/tracking.rs
To give a home to those generally useful datastructures which are not
found elsewhere, or are not sophisticated enough to begin living a life
of their own, we introduce the `radicle-data` crate.
For starters, a couple of non-empty container types are exported.
> data: kickstart the radicle-data crate

- e2e/Procfile
- e2e/compose.yaml
Allows to bootstrap a peer on the host against the bootstrap container.
Note that the network indeed converges.
To prevent conflicts, a different port for the Procfile bootstrap node
is chosen.
> e2e: expose container ports on the host

- data/Cargo.toml
- data/src/bounded.rs
- data/src/lib.rs
- data/src/nonempty.rs
- e2e/compose.yaml
- librad/src/net/peer.rs
- librad/src/net/quic/endpoint.rs
- librad/tests/smoke/gossip.rs
Popped off the reading list: QUIC stateless retry is essentially a
defense against UDP reflection attacks, adding one (small) roundtrip to
the handshake.
> net: use stateless retry

- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/membership/periodic.rs
- librad/src/net/quic.rs
To avoid connections being gc'ed when idling, there was a mechanism to
tickle all active ones in the current partial view. So far that was
placed after the await point of the stream processing, so it would not
be executed. To remedy the change tries to be barry algebraic by
introducing a new variant explicitely for the tickler. It does the job
but doesn't quite hit the mark as the current accept::periodic
implementation is very much tailored to the tick tocking - Likely
warrants a bit of a rework.
> net: promote periodic membership tickle

- git-helpers/src/bin/remote/main.rs
- git-helpers/src/remote_helper.rs
Users of `radicle_git_helpers::remote_helper` can now configure the signer. This allows us to create integration tests with fast crypto [1].
[1]: https://github.com/radicle-dev/radicle-upstream/issues/1614
> Remote helper signer can be configured

- librad/src/git/types/reference.rs
This did not delegate to RefsCategory for some reason, failing to parse
anything but "heads" and "rad". Tag replication thus likely never worked
properly.
> git: fix category parsing in impl TryFrom<&Urn> for Reference

- data/src/bounded.rs
As the Extend trait promises to consume the iterator, we make it clear
that this may leave unconsumed elements in the iterator.
> data: add a way to extend bounded types

- librad/Cargo.toml
- librad/src/lib.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/broadcast.rs
- librad/src/net/protocol/control.rs
- librad/src/net/protocol/error/internal.rs
- librad/src/net/protocol/event.rs
- librad/src/net/protocol/info.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/recv/gossip.rs
- librad/src/net/protocol/io/send/rpc.rs
- librad/src/net/protocol/membership.rs
- librad/src/net/protocol/membership/hpv.rs
- librad/src/net/protocol/membership/partial_view.rs
- librad/src/net/protocol/membership/periodic.rs
- librad/src/net/protocol/membership/rpc.rs
- librad/src/net/protocol/membership/tick.rs
- librad/src/net/protocol/tick.rs
- librad/tests/smoke/interrogation.rs
This is a long-standing open issue: we need to make sure that collection
types are always bounded on the wire.
Note that, while morally a set, set semantics were not captured
precisely:
1. For establishing a connection, we take the union of the seen and
advertised addresses, with a bias towards the former.
2. For maintaining the seen addresses, we bias towards the more recent
information.
1. needs to be computed at runtime anyways, while 2. is much simpler to
maintain using a (small) Vec instead of a specialised insertion-ordered
set type. We thus spare ourselves the nuisance of having to thread
through an Ord or Hash constraint on the datatype level.
> net: use a bounded vec for propagated address info

- librad/Cargo.toml
- librad/src/lib.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
- librad/src/net/protocol/broadcast.rs
- librad/src/net/protocol/control.rs
- librad/src/net/protocol/error/internal.rs
- librad/src/net/protocol/event.rs
- librad/src/net/protocol/info.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/recv/gossip.rs
- librad/src/net/protocol/io/send/rpc.rs
- librad/src/net/protocol/membership.rs
- librad/src/net/protocol/membership/hpv.rs
- librad/src/net/protocol/membership/partial_view.rs
- librad/src/net/protocol/membership/periodic.rs
- librad/src/net/protocol/membership/rpc.rs
- librad/src/net/protocol/membership/tick.rs
- librad/src/net/protocol/state.rs
- librad/src/net/protocol/tick.rs
- librad/tests/smoke/interrogation.rs
This is a purely mechanical change, as part of continuously grooming the
scrolls.
> net: move protocol state struct into its own module

- librad-test/src/rad/identities.rs
- librad/src/git/p2p/server.rs
- librad/tests/smoke/mod.rs
- librad/tests/smoke/saturation.rs
Trying to replicate a dead-lock that we witness in a scenario between
a client and a seed node.
The real world scenario:
The client periodically creates a test every few seconds. On the 12th
project the seed does not replicate it. There's no output from logging
nor GIT_TRACE_PACKET.
This test scenario:
Peer 1 creates 12 projects and Peer 2 tries to replicate them all in a
loop. The dead-locking is not witnessed and the test passes.
> smoke: saturate a peer

- librad/src/git/p2p/server.rs
We allow `allowanysha1inwant`. This allows the server to request a
reference as a `want`, since one side might have updated its tips during
a mutual fetch.
> p2p: allow any in upload-pack

- librad/src/git/fetch/specs.rs
We don't want to force the update of any of these references (despite
force not necessarily being respected
https://github.com/radicle-dev/radicle-link/issues/645).
> fetch: do not force signed_refs

- daemon/src/seed.rs
- daemon/src/state.rs
- daemon/tests/internal.rs
- daemon/tests/replication.rs
- daemon/tests/working_copy.rs
In conjunction with #650, we see async tests intermittently hanging
indefinitely when the per-test runtime shuts down. This may have to do
with some blocking operations in `daemon` not being properly
`spawn_blocking`-ed (and thus blocking the single runtime thread), or
some mysterious interaction with threads spawned from within the async
program.
In any case, using the multi-threaded runtime appears to fix it.
> daemon: run all async tests on the multi-threaded runtime

- librad/src/net/protocol/io/recv/gossip.rs
Another oversight when switching to unidirectional streams: the
unsolicited state occurs when partial view states diverge, but the
remote end will never know because closing the stream has no effect
anymore. Thus, send a DISCONNECT message in this case to sync states.
> net: send disconnect on unsolicited broadcast

- librad/src/net/protocol/membership/hpv.rs
If the number of peers currently active in the view is larger than the
configured max, the calculation to pick a random number of peers from
the passive list will panic. If the subtraction on usize underflows it
will return `usize::MAX` which in turn will cause trouble in the
allocation code of raw vectors as it hits the max capacity branch in the
alloc_guard. The reason this is happening in the first is that
`choose_mutliple` of the rand crate creates a `Vec` with the given
`amount` in our case `n`. See links below to decent into madness:
https://github.com/rust-random/rand/blob/30d2d98df5d09c524a30c8772fc7c8b203f5b70a/src/seq/mod.rs#L468
https://github.com/rust-lang/rust/blob/master/library/alloc/src/raw_vec.rs#L188
https://github.com/rust-lang/rust/blob/e5f83d24aee866a14753a7cedbb4e301d …
> protocol: Guard against underflow in promotion

- librad/src/net/protocol/io/recv/git.rs
- librad/tests/smoke/fetch_limit.rs
The refs updated as a side-effect of rere shall be announced. This is a
prerequisite for grafting, which happens independent of gossip
membership.
Note that this will cause amplification while client-initiated announce
is still in effect.
> net: announce after rere

- librad/src/net/protocol/io/recv/git.rs
- librad/tests/smoke/fetch_limit.rs
Running both concurrently makes things harder to reason about. Better
opportunities for optimisation and interleaving may arise with git
protocol v2.
> net: run rere after serving the fetch

- .github/workflows/fast.yaml
- ci/test-fast
- radicle-link-test/Cargo.toml
- radicle-link-test/src/daemon.rs
- radicle-link-test/src/daemon/common.rs
- radicle-link-test/src/integration/daemon/common.rs
- radicle-link-test/src/integration/daemon/gossip.rs
- radicle-link-test/src/integration/daemon/internal.rs
- radicle-link-test/src/integration/daemon/replication.rs
- radicle-link-test/src/integration/daemon/working_copy.rs
- radicle-link-test/src/lib.rs
In the process, confine setup/teardown boilerplate in a `Harness` struct
similar to the `testnet`, ensuring, amongst other things, that the
temporary directories outlive the runtime.
Also some error context + proper spawn_blocking where advisable.
> testing: move daemon test to centralisised test crate

- librad/src/net/protocol/io/connections.rs
We log error conditions explicitly, and the auto-error just adds noise
when shutting down gracefully.
> net: avoid error log when endpoint is shutting down

- daemon/src/peer/announcement.rs
- librad/src/git/p2p/transport.rs
- radicle-link-test/src/daemon/common.rs
- radicle-link-test/src/rad/testnet.rs
The nested runtime for the git p2p transport appears to cause the global
runtime to get stuck on shutdown for not entirely clear reasons (some
`thread::unpark` seems to get lost). Adding a small timeout to keep
runaway tasks running seems to fix that, while still preventing blocking
tasks to access already-dropped temporary directories.
> testing: shutdown runtime with timeout

- Cargo.toml
The patched git2 can be found in radicle-dev/git2-rs. That repo in turn uses radicle-div/libgit via a submodule in it's `libgit2-sys/libgit` folder.
I've tested running this with a couple of upstreams and a seed built against it and the `rere` problem dissappears.
> Point everything at the patched git2

- git-helpers/Cargo.toml
This is only needed for testing, which moved to the test crate. Cargo
also gets confused due to duplicate output file name.
> git-helpers: remove executable

- deny.toml
- librad/Cargo.toml
Cargo patch won't use the patched version if it can satisfy the
dependency in other ways, e.g. via a newer version of the crate. Due to
the wonders of caret dependencies, we thus need to pin git2-rs to the
version used in the patch override.
> fix git2-rs patch not getting used

- .buildkite/env
These are created by the `env` script itself.
> ci: keep cache subdirs intact when pruning

- librad/src/net/protocol/interrogation/xor.rs
- librad/src/net/protocol/io/recv/gossip.rs
- librad/src/net/protocol/io/recv/interrogation.rs
- librad/src/net/protocol/io/recv/membership.rs
Should avoid excessive decoding attempts in pathological cases (see also #680).
> net: buffer framed reads

- daemon/src/config.rs
When the sender for the seed nodes is dropped we stop emitting values from the discovery stream instead of panicking.
We’re [seeing these panics](https://buildkite.com/monadic/radicle-upstream/builds/9127#cc84739f-dd04-40e4-88e7-10367875b581/6-169) regularly in Upstream CI when the node is reloaded.
> daemon: don’t panic when discovery stream ends

- librad/src/git/identities/any.rs
- librad/src/git/identities/local.rs
- librad/src/git/identities/person.rs
- librad/src/git/identities/project.rs
- librad/src/git/include.rs
- librad/src/git/local/transport.rs
- librad/src/git/p2p/server.rs
- librad/src/git/refs.rs
- librad/src/git/replication.rs
- librad/src/git/storage.rs
- librad/src/git/storage/fetcher.rs
- librad/src/git/tracking.rs
- librad/src/git/types/remote.rs
- librad/src/identities/git/load.rs
- librad/src/net/protocol/broadcast.rs
- librad/src/net/protocol/io/graft.rs
- test/src/git.rs
The `err` parameter for the `tracing::instrument` macro logs at error
level unconditionally when the `Result`-returning function returns, err,
`Err`. This was once useful for debugging, but nowadays adds noise: it
is often hard to tell where the log line comes from, it's not always an
error (ie. it might be handled), or multiple log lines are emitted for
the same error condition.
Thus, remove it everywhere.
> librad: remove `err` logging from instrument macro

- daemon/src/peer.rs
- e2e/src/bin/ephemeral-peer.rs
- librad/src/executor.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/streams.rs
- librad/src/net/quic/endpoint.rs
- seed/src/lib.rs
- test/src/rad/testnet.rs
Latest installment of the cancellation saga: the shutdown sequence for
an endpoint needs to be carefully grafted in order to not stall blocking
tasks (which call back into the async context), and it is advisable to
call `wait_idle` on the endpoint. In turn, our aggressive cancellation
policy needs to be loosened a bit to not immediately abort everything,
but drain outstanding tasks. Iow, if tests hand on shutdown, it is now a
programmer error.
Arguably, the return type of `accept` is now pretty weird (one future
for shutdown, and another one to actually drive the accept loop). Not
sure if there is a better formulation, as we are also constrained by
opaque types.
Note that the `menage` tests are still failing, which appears to depend
on whether the force-flag-honouring libgit2 is picked up …
> io: graceful shutdown

- git-helpers/src/remote_helper.rs
Without a public field the config struct cannot be used to configure the remote helper.
> git-helpers: make remote helper config fields public

- docs/rfc/0686-asciidoc.adoc
[Rendered](https://github.com/radicle-dev/radicle-link/blob/rfc/asciidoc/docs/rfc/0000-asciidoc.adoc)
> RFC: Standardise on AsciiDoc instead of Markdown

- docs/rfc/0682-application-architecture.adoc
RFC #673 starts out by describing various functionality in terms of "capability"
traits". While a worthwhile exercise for mapping out "core" functionality and
defining surface APIs, it is difficult to see how the RFC can reach its stated
goal of "[allowing to] compose them easily, allowing upstream consumers to
mix-and-match them in any way they desire" without committing to a concrete
application architecture.
Specifically, it does not consider that different applications can have (very)
different lifecycles, yet will need certain ways to communicate with each other
(eg. to be notified of certain changes). It also doesn't talk about key
management and authentication, process management, and the distinction between
"online" and "offline" operations (recall that only one instance per …
> RFC: Application Architecture

- daemon/src/peer/announcement.rs
- daemon/src/state.rs
- librad/src/git/identities/any.rs
- librad/src/git/identities/common.rs
- librad/src/git/identities/person.rs
- librad/src/git/identities/project.rs
- librad/src/git/identities/relations.rs
- librad/src/git/local/transport.rs
- librad/src/git/refs.rs
- librad/src/git/replication.rs
- librad/src/git/storage.rs
- librad/src/git/storage/fetcher.rs
- librad/src/git/storage/pool.rs
- librad/src/git/storage/read.rs
- librad/src/git/tracking.rs
- librad/src/net/peer.rs
- librad/src/net/peer/error.rs
- librad/src/net/peer/storage.rs
- librad/src/net/protocol.rs
- librad/src/net/protocol/io/graft.rs
- librad/src/net/protocol/io/recv/interrogation.rs
- librad/src/net/protocol/state.rs
- test/src/test/integration/librad/scenario/menage.rs
- test/src/test/integration/librad/smoke/clone.rs
- test/src/test/integration/librad/smoke/gossip.rs
- test/src/test/integration/librad/smoke/graft.rs
- test/src/test/unit/librad/git/project.rs
Fixes #461
We introduce the read-only variant of Storage. The use of this variant
implies that it will be used for read-only purposes, and so it does not
hold a signer.
Storage is re-formulated to be a combination of the read-only store
along with the signer and fetchers.
> storage: introduce read-only type

- librad/src/net/protocol.rs
- librad/src/net/protocol/accept.rs
It's moved, so can be pinned in the handler function.
> protocol: avoid boxing of control stream

- daemon/src/state.rs
- librad/src/git/replication.rs
- test/src/test/integration/daemon/replication.rs
Fixes #708 
We add `rad/id` at the top level and create a symbolic ref between `rad/id` and `rad/self` for each tracked peer.
In the `daemon` code I changed the `get_user` function to return a regular `Person` document and added `get_local` for getting the local identity.
I chose to add the test to `daemon/replication` because I thought it would have fitted with the `menage` tests but they're no bueno right now.
> replication: create rad/id and rad/self symref

- librad/src/profile.rs
- librad/src/profile/id.rs
- test/src/test/unit/librad/profile.rs
While scoping out the introduction of creating, getting, and setting
profiles, I saw some room for refactoring to better see the flow of
profile creation and loading.
This patch introduces the `profile::id` module which contains the
`ProfileId` type. It surfaces the many ways to construct a ProfileId:
* From a UUID
* Read from RAD_PROFILE
* Read from active_profile
* Read from active_profile or default to creating one
Before this change, a profile ID was simply a String, but now that it is
behind a newtype wrapper, it's more obvious that it must go through
validation during construction.
The other introduction to this change is the RadHome enum which captures
where the Profile is living: XDG or some given Root.
The construction of a Profile is now computed in terms of RadHome and …
> profile: refactor Profile

- daemon/Cargo.toml
- daemon/src/config.rs
- daemon/src/peer.rs
- daemon/src/peer/gossip.rs
- daemon/src/peer/include.rs
- daemon/src/peer/run_state.rs
- daemon/src/peer/run_state/running_waiting_room.rs
- daemon/src/peer/subroutines.rs
- daemon/src/peer/sync.rs
- daemon/src/project/checkout.rs
- daemon/src/project/create/validation.rs
- daemon/src/state.rs
We replace the `log` crate with `tracing` for `daemon` and clean up some logging statements.
> daemon: use tracing crate and improve logging

- librad/src/profile.rs
- librad/src/profile/id.rs
- test/src/test/unit/librad/profile.rs
Adding functionality for management of `Profile`s. Specifically the following functions:
* `new`
* `get`
* `set`
* `list`
TODO:
> profile: management of profiles

- daemon/src/peer/subroutines.rs
Logging the `Subrioutines` input is quite noisy because we have frequent “tick” events that often have no effect. If they have an effect we should add logging statements in those places.
> daemon: only log with trace level for subroutines

- librad/src/net/protocol.rs
We fix a deadlock when we wait for the quic endpoint to become idle.
The deadlock happens when we wait for `endpoint.wait_idle()` while we are simultaneously still trying to connect to a remote that does not respond (i.e. it neither accepts nor refuses the connection) in `connect` called by `librad::net::protocol::io::discovered()`.
To make `endpoint.wait_idle()` future finish we need to advance the connection task so we drop it after the future has finished instead of before.
> librad: fix deadlock when waiting for idle

- Cargo.toml
- deny.toml
- git-protocol/Cargo.toml
- git-protocol/src/fetch.rs
- git-protocol/src/lib.rs
- git-protocol/src/packwriter.rs
- git-protocol/src/take.rs
- git-protocol/src/upload_pack.rs
- test/Cargo.toml
- test/src/test/integration.rs
- test/src/test/integration/git_protocol.rs
- test/src/test/unit/git_protocol.rs
- test/src/test/unit/git_protocol/take.rs
- test/src/test/unit/git_protocol/upload_pack.rs
Introduces a new crate with the lower-level machinery for handling
replication based on git protocol v2.
> git-protocol: git protocol v2 machinery

- e2e/src/logging.rs
- test/src/logging.rs
We use the test writer for `tracing_subscriber` so that log output is captured by the tests. This also allows us to increase the default verboseness of the log outputs which provides more information when the tests fail.
> tests: use test writer for fmt subscriber

- librad/src/net/protocol.rs
- librad/src/net/protocol/control.rs
- librad/src/net/protocol/info.rs
- librad/src/net/protocol/io.rs
- librad/src/net/protocol/io/connections.rs
- librad/src/net/protocol/io/recv/interrogation.rs
- librad/src/net/protocol/io/send/rpc.rs
- librad/src/net/protocol/state.rs
- librad/src/net/protocol/tick.rs
- librad/src/net/quic.rs
- librad/src/net/quic/connection.rs
- librad/src/net/quic/connection/tracking.rs
- librad/src/net/quic/endpoint.rs
See message of most recent commit.
_Note: `quinn:TransportConfig::max_concurrent_*_streams` applies to the remote end, so we can change this to a more restrictive value only after this was rolled out_
> Retain outgoing uni streams

- librad/src/git/identities/person.rs
- librad/src/git/identities/project.rs
- librad/src/git/replication.rs
- test/src/rad/identities.rs
- test/src/test/integration/librad/scenario.rs
- test/src/test/integration/librad/scenario/updated_delegate.rs
We have the following steps:
* Peer 1 creates a Person document
* Peer 2 replicates this Person
* Peer 1 updates Person document
* Peer 1 creates Project delegating to new Person document
* Peer 2 attempts to replicate the Project, but fails with error below
Error:
```
Revision 7bb4bbce268d89a62e1962f5dded7a9f68c9e665 of 4b84e8407d602317b01f22207908dbea1d9d4e17 not in ancestry path of eada5419806f643d402c92b790c9b471098f1e81
```
The error originates from [`updated_person`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/identities/git.rs#L781), which seems to not consider the fact that the `Person` in the delegate is a fast-forward of the `Person` that Peer 2 knows about at the top-level. Instead, it only checks that the `Person` delegate was a previous version of the …
> identities: updated delegation causes replication failure

- git-protocol/Cargo.toml
The functionality used here was tagged and released yesterday, so we do
not have a reason to use git dependencies anymore.
> git-protocol: switch to gitoxide deps from crates.io

- git-protocol/Cargo.toml
- git-protocol/src/fetch.rs
- git-protocol/src/ls.rs
- git-protocol/src/transport.rs
gitoxide's `git-protocol` released a breaking change from version 0.8.0
to 0.8.1. Satisfy the new API, require a lower bound of 0.8.1, and hope
for the best.
> git-protocol: fix bad gitoxide release

- git-protocol/Cargo.toml
The faulty 0.8 got yanked, so move on to 0.9.
Cf. 90a024f3 (git-protocol: fix bad gitoxide release, 2021-08-16)
> git-protocol: bump gitoxide `git-protocol`

- git-ext/Cargo.toml
- git-ext/src/oid.rs
Impl conversions for `Oid` to and from `gitoxide`s `git-hash` types.
`git2::Oid` remains the canoncial representation, so the conversion is
not always free.
> git-ext: gitoxide conversions for Oid

- daemon/src/peer/announcement.rs
Fixes #757 
The previous implementation used `join` over `into_qualified`, this
would result in the following in a reference of the form `rad/id`. This
reference can be ambiguous -- either meaning `refs/rad/id` or
`refs/heads/rad/id`.
We know, however, that this should be `refs/rad/id`. So using the
`into_qualified` function would give us the correct path of
`refs/rad/id`.
> daemon: qualify announcement path

- seed/src/lib.rs
When calling `Node::track_project`, it might very well be that the
project/peer is already tracked, which would result in unnecessary
broadcast traffic. Thus, don't emit any events in this case.
Also, change the order of `track` and `replicate` to ensure we
do actually fetch the newly-tracked peer's view. Additionally, we can
skip `replicate` if we already tracked the peer, as subsequent broadcast
messages won't be considered uninteresting.
Ref #734
> seed: consider if tracking relationship was already established

- Cargo.toml
- clib/Cargo.toml
- clib/src/keys.rs
- clib/src/storage.rs
- deny.toml
- link-crypto/Cargo.toml
- link-crypto/src/keys.rs
Depends on https://github.com/radicle-dev/radicle-keystore/pull/21
> clib: ssh-agent storage

- daemon/src/peer/run_state.rs
We only send information about gossip messages to the waiting room if the waiting room is waiting for them.
> fix: waiting room handles gossip only if it knows URN

- docs/rfc/0696-p2p-node.adoc
[Rendered](https://github.com/radicle-dev/radicle-link/blob/xla/rfc-p2p-node/docs/rfc/0696-p2p-node.adoc)
> RFC: Peer-to-peer node

- librad/src/git/local/transport.rs
- librad/src/git/refs.rs
- librad/src/git/storage/fetcher.rs
- test/src/rad/identities.rs
- test/src/test/integration/librad/smoke/fetch_limit.rs
When two `Refs::update` race, only one of them can succeed, because the
ref update only succeeds if the expected parent commit is what the ref
currently points to (ref updates are atomic). While there is a chance
that the winning update commits a slightly outdated view of the refs
tree, this is tolerable, because every modification of the namespace
will trigger a sigrefs update, and thus the state converges.
Not so great, however, is to propagate the commit failure due to a
modified parent as an error, as this may interrupt the replication flow,
leaving the namespace in a potentially half-arsed state.
Therefore, teach `Refs::update` to ignore this kind of error, and return
the most recent committed state instead.
Fixes #761
> git: ignore error due to concurrent sigrefs update
